### ISSUE TITLE
Displaying raw transaction

### ISSUE THREAD

**Issue by onur-ozkan** [smk762/komodo-install-explorer#1]
At least for devs, it would be really useful being able to see/dump raw transaction values on the explorer (an example, iobscan provides such functionality under the JSON tab https://irishub.iobscan.io/#/txs/245E98A23454A138233A0D3DB2BCEDF96F5BEAF83421C99DEB7D514CC0973505).

**Comment by DeckerSU** [comment]
Currently it's possible via API, for example, for txid `568ca0794ee03443673dd5aae618b6dc928e11a3b912761421d8c91768a8849b` you can call:

- https://kmdexplorer.io/insight-api-komodo/rawtx/568ca0794ee03443673dd5aae618b6dc928e11a3b912761421d8c91768a8849b (`rawtx`)
- https://kmdexplorer.io/insight-api-komodo/tx/568ca0794ee03443673dd5aae618b6dc928e11a3b912761421d8c91768a8849b (`tx`)

The last one will give you JSON like this:

```json
{"txid":"568ca0794ee03443673dd5aae618b6dc928e11a3b912761421d8c91768a8849b","version":4,"locktime":0,"vin":[{"txid":"801c2f6680f2e42ce2a8d4c65b273bd3ece5f1677d0fc0824cca484ae5abae8b","vout":0,"sequence":4294967295,"n":0,"scriptSig":{"hex":"483045022100d397e8fde3bb7213a14e2e8154c1c83750c7bfb5cc5575f6dcf169be5a3732a402201e9303a7b5fa7cf9d744cb589eeb565ad864ea67b52f496ffcabf4947a6c25ad01","asm":"3045022100d397e8fde3bb7213a14e2e8154c1c83750c7bfb5cc5575f6dcf169be5a3732a402201e9303a7b5fa7cf9d744cb589eeb565ad864ea67b52f496ffcabf4947a6c25ad[ALL]"},"addr":"RDZaLiENRUnckP57oRxLznYmFM5bV9PaZV","valueSat":10000,"value":0.0001,"doubleSpentTxID":null}],"vout":[{"value":"0.00005000","n":0,"scriptPubKey":{"hex":"21020e46e79a2a8d12b9b5d12c7a91adb4e454edfae43c0a0cb805427d2ac7613fd9ac","asm":"020e46e79a2a8d12b9b5d12c7a91adb4e454edfae43c0a0cb805427d2ac7613fd9 OP_CHECKSIG","addresses":["RXL3YXG2ceaB6C5hfJcN4fvmLH2C34knhA"],"type":"pubkeyhash"},"spentTxId":null,"spentIndex":null,"spentHeight":null},{"value":"0.00000000","n":1,"scriptPubKey":{"hex":"6a20b2128e0f64af4573ae7d0001eea50e5b00c16d58c7daaa819eb8b55719285fcb","asm":"OP_RETURN b2128e0f64af4573ae7d0001eea50e5b00c16d58c7daaa819eb8b55719285fcb"},"spentTxId":null,"spentIndex":null,"spentHeight":null}],"vjoinsplit":[],"blockhash":"0d444c7a4afbebf057187eda445fbcb1fcf0cb5c05349a5b5bdbb0c6b667b966","blockheight":3680040,"confirmations":3,"time":1700232295,"blocktime":1700232295,"valueOut":0.00005,"size":230,"valueIn":0.0001,"fees":0.00005,"fOverwintered":true,"nVersionGroupId":2301567109,"nExpiryHeight":3680240,"valueBalance":0,"spendDescs":[],"outputDescs":[]}
```
Is this what you want?

**Comment by DeckerSU** [comment]
Or you want a `JSON` button like this:
![image](https://github.com/smk762/komodo-install-explorer/assets/22120003/82565603-3a68-4900-8136-03ae7251229b)
In explorer UI?

**Comment by onur-ozkan** [comment]
I was asking for adding it to UI which will help us by not requiring manual effort to see the raw data. Even redirecting to the API response like https://kmdexplorer.io/insight-api-komodo/tx/568ca0794ee03443673dd5aae618b6dc928e11a3b912761421d8c91768a8849b this can be enough from a `Raw Data` button.

**Comment by DeckerSU** [comment]
> I was asking for adding it to UI which will help us by not requiring manual effort to see the raw data.

Enjoy. Button have been added:

![image](https://github.com/smk762/komodo-install-explorer/assets/22120003/f5061e61-4077-4067-95d8-353179fb69b1)

https://kmdexplorer.io/tx/7f3cda0ef76c29e0ad9864778e8300099c20a9fd17770cecaa852061202b8e3f

**Comment by onur-ozkan** [comment]
Thank you!
